### Send POST request with json body
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "email": "closeup1202@naver.com",
  "password": "12345@@"
}

### Send POST request with json body
POST http://localhost:8080/user/password/change
Content-Type: application/json

{
  "email": "closeup1202@naver.com",
  "currentPassword": "12345@@",
  "newPassword": "12345!!"
}

### Send POST request with json body
POST http://localhost:8080/user/signin
Content-Type: application/json

{
  "email": "closeup1202@naver.com",
  "password": "12345@@"
}

### Send POST request with json body
GET http://localhost:8080/test