### Send POST request with json body
POST http://localhost:8080/signin
Content-Type: application/json

{
  "email": "closeup1202@naver.com",
  "password": "sjrsjr123@"
}

### Send POST request with json body
GET http://localhost:8080/test